include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    # ferry graphql
    - "**/*.g.dart"
    - "**/*.ast.gql.dart"
    - "**/*.gql.dart" # IDEでauto_importを利用したい場合は外す
    # freezed 
    - "**/*.freezed.dart"
    # https://www.fluttericon.com/ から生成したファイル
    - "**/app_icons.dart" # IDEでauto_importを利用したい場合は外す
  
  strong-mode:
    # 暗黙的な型変換を禁止する
    implicit-casts: false

linter:
  rules:
    sort_pub_dependencies: false # pubを種類ごとに配置しているため
    avoid_classes_with_only_static_members: false # classを名前空間として使いたいため
    use_build_context_synchronously: false # 一旦見送り cf. https://twitter.com/_mono/status/1390556226853904384
    lines_longer_than_80_chars: false # 80は無理 120で設定する方法がなかったのでfalseにした
    use_key_in_widget_constructors: false # key渡すのMustじゃないと思うのでfalse
    always_put_control_body_on_new_line: false # 短く書きたいので
    flutter_style_todos: false # 謎のTODOのスタイル不要
    no_default_cases: false # switch文のdefault記述要
    prefer_const_constructors: true
    empty_statements: true
    no_duplicate_case_values: true
    annotate_overrides: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    prefer_conditional_assignment: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    unnecessary_null_in_if_null_operators: true
    prefer_relative_imports: true
    avoid_relative_lib_imports: true